### ISSUE TITLE
Submap selection is not visible on the Map View window

### ISSUE THREAD

**Issue by rekyuu** [PunishedPineapple/WaymarkPresetPlugin#10]
Sub-Map radio buttons seem to be hidden under the map image but are consistently hidden due to the map expanding vertically with the window:

![image](https://user-images.githubusercontent.com/14059899/111234617-8e1ffa80-85b4-11eb-9920-f0420750b6b7.png)

**Comment by PunishedPineapple** [comment]
The map maintains a square aspect ratio, sizing to whichever dimension it can without clipping any off.  If you expand the window vertically without making it bigger horizontally, the buttons should be right there, like this: 

![image](https://user-images.githubusercontent.com/50609717/111236285-76e70a00-85c0-11eb-8881-e7db991a2c6e.png)

That being said, if multiple people are having issues using it (you're not the first to not see the buttons), then it means that it's a poor UI choice.  I'll probably move the sub-map selection to another window.  I would prefer to have them over the map like in-game, but that would probably be a nightmare to do with ImGui.  Anyway, they're accessible, so it won't be changed right now, but probably next release that's done for other things.

**Comment by rekyuu** [comment]
I made a PR that changes the layout from radio buttons to a dropdown menu that should show by default on applicable maps.

https://github.com/PunishedPineapple/WaymarkPresetPlugin/pull/11

**Comment by PunishedPineapple** [comment]
Included with 1.2.0.2 release.
