### ISSUE TITLE
Sorting/reorganizing waymarks (not zones)

### ISSUE THREAD

**Issue by ThatsNotAName** [PunishedPineapple/WaymarkPresetPlugin#14]
Is there a way to sort waymarks within the zones so that you can organize them for the autoload presets feature? If you have more than 5 waymarks its a bit frustrating and redundant the way you currently have to organize them by deleting and importing them in the order you want. If there is a way to do this already please let me know as I can't figure it out :( . For example I want to organize these markers in the way listed here:

<details>
  <summary>Click to show image.</summary>
  
  ![Example 1](https://i.imgur.com/7Cpw0QS.png)
  
  </details>

**so that they get automatically imported this**:

<details>
  <summary>Click to show image.</summary>
  
 ![Example 2](https://i.imgur.com/G6Eua9s.png) 
  
  </details>
Sorry if the images are a bit messy but I wasn't sure how to type what I meant. Thanks in advance! :)

**Comment by PunishedPineapple** [comment]
At this time, the only way to change the order is to delete and reimport like you said, or go into the `WaymarkPresetPlugin.json` config file (should be in `%appdata%\XIVLauncher\pluginConfigs` by default), and move each preset block around manually.  Their positions relative to each other in that file determine their order in the gui.  If you do this, please make a backup copy of the file beforehand in case you make a mistake.

I will look into either drag and drop reordering, or adding buttons to move an item up/down in the list, but don't expect anything in the immediate future.

**Comment by PunishedPineapple** [comment]
Drag and drop preset reordering was added with v1.3.2.0.
