### ISSUE TITLE
Needs Update 6.0

### ISSUE THREAD

**Issue by DiggityMan420** [PunishedPineapple/WaymarkPresetPlugin#15]
No showing up as updated to 6.0 and plans to do so?

**Comment by PunishedPineapple** [comment]
It's not been updated.  I've been playing through the MSQ and helping my friends get leveled up.  I do plan to update it, hopefully by early next week.  If you really need something, the offline tool that I have in one of my other repos here *should* work (I know, not great with queues like they are).

Sorry for the delay.

**Comment by Aireil** [comment]
This sig broke: https://github.com/PunishedPineapple/WaymarkPresetPlugin/blob/master/WaymarkPresetPlugin/MemoryHandler.cs#L56
`E8 ?? ?? ?? ?? 41 38 44 24` seems to be the new one.

[There's also a change here where Unknown10 doesn't exist anymore.](https://github.com/PunishedPineapple/WaymarkPresetPlugin/blob/master/WaymarkPresetPlugin/ZoneInfoHandler.cs#L36-L58) It got changed to a LazyRow:
![q0lKnIx](https://user-images.githubusercontent.com/33433913/145509106-91baf29d-25d7-41c2-9c25-82676c1e596e.png)
I tried to fix it, but I get a butch of Unknown Duty in my library, so I guess either my fixes don't work or something else is broken.

Just sharing what I found 😄 .

**Comment by PunishedPineapple** [comment]
Thanks for the info!  I finally got a few free minutes tonight and updated it.  Should be up whenever the PR is approved.  Sorry again for the delay.
