### ISSUE TITLE
Save signs as well as waymarks?

### ISSUE THREAD

**Issue by amki** [PunishedPineapple/WaymarkPresetPlugin#18]
Would it be possible to also save the current signs on party members? I'd say saving this mark is on player_id would be nice

**Comment by PunishedPineapple** [comment]
You can already do this in-game via macro:  Something like the following should work:
```
/mk ignore1 <1>
/mk bind1 <2>
/mk bind2 <3>
/mk ignore2 <4>
/mk attack1 <5>
/mk attack2 <6>
/mk attack3 <7>
/mk attack4 <8>
```
The reference for this text command is: https://na.finalfantasyxiv.com/lodestone/playguide/db/text_command/4348eed9de5/

Granted, if you go into a fight as multiple roles, you'll need multiple macros to match your party sort order, but it is what it is.  Saving signs is pretty far out of scope for this plugin though.
