### ISSUE TITLE
Y,Z coordinate are interchanged

### ISSUE THREAD

**Issue by Mocha313** [PunishedPineapple/WaymarkPresetPlugin#19]
![image](https://user-images.githubusercontent.com/4688005/155889195-f3b3958e-d9b4-447c-8ca5-b66fb80045a9.png)
It should be 0,10,75 instead of 0,75,10

**Comment by PunishedPineapple** [comment]
It's correct as it is, unfortunately.

The game uses a right-handed coordinate system where the X axis is East and West, the Y axis is up and down, and the Z axis is South and North.  When you're viewing the map, you're projecting the XZ plane into a 2D coordinate system where the X is East and West, and Y is South and North.

The game obscures this when it presents its fake, scaled coordinate system in \<pos\> and \<flag\> chat links, and in the coordinate readouts on the map and minimap windows, but I'm not willing to do so, sorry.  Anyone manually editing the coordinates of waymarks should probably have a basic understanding of the game's coordinate system anyway.

I might put in a help marker that explains the coordinate system though, so I'm going to leave this issue open as a reminder to look into where would be best to add that.

**Comment by PunishedPineapple** [comment]
A help marker was added to the map view window in v1.3.2.0 that explains the coordinate systems used.
