### ISSUE TITLE
in e12s map view

### ISSUE THREAD

**Issue by tssailzz8** [PunishedPineapple/WaymarkPresetPlugin#22]
i see it not true in e12s map view
![image](https://user-images.githubusercontent.com/52206101/167281605-a70510b8-4a45-4e47-b1b5-903f17045067.png)

**Comment by PunishedPineapple** [comment]
You need to select sub-map 5 in the dropdown to see them on the correct map.  e12s is somewhat unique in that the duty does not start on the first submap.  Sadly it's not something that I can control right now.  I'm sorry.

**Comment by tssailzz8** [comment]
it only in e12s?

**Comment by PunishedPineapple** [comment]
Other zones have multiple submaps, but for all others I know of, you enter the instance on submap 1.
