### ISSUE TITLE
Feature Request: Round coordinates to nearest digit button

### ISSUE THREAD

**Issue by sSasha-uwu** [PunishedPineapple/WaymarkPresetPlugin#28]
When copying waymark sets from PF I often end up using this plugin and manually rounding each coordinate in the preset so that every waymark is equidistant. A button that does this would be really helpful and I imagine not that difficult to implement.

**Comment by PunishedPineapple** [comment]
Not difficult to implement, but it's added UI bloat for something that doesn't need to be done that often, and I'd like to avoid that, sorry.

Additionally, rounding doesn't necessarily make waymarks equidistant; radially symmetric positions (such as clock spots) will never all be at integer coordinates by definition (unless you only have 2 or 4 markers that are only on the same of cardinals or intercards), so this feels very niche.

Edit: Actually I guess you could be talking about what people are doing for the new Ex with cards out and intercards in, but still it's like 30 seconds per waymark set to square them up, and I just don't think that time spent once per preset is worth adding more UI.
