### ISSUE TITLE
Text command to export preset to in-game slot

### ISSUE THREAD

**Issue by Sharparam** [PunishedPineapple/WaymarkPresetPlugin#7]
Something like:

`/pwaymark export 2 3`

To export saved preset with ID 2 to in-game waymark slot number 3.

I was thinking this would make it easier to make macros that print the strats for a fight as well as placing waymarks after importing them from the saved presets (since the direct placement feature can be unstable).

So a macro would be something like:

```
/pwaymark export 2 3
/wmark preset 3
/p Fight strategies go here
```

Currently it seems one would have to use the GUI to manually export a saved preset, or use the feature that overwrites all the in-game presets with those saved for a zone, but that is a bit heavy-handed I feel.

**Comment by PunishedPineapple** [comment]
There were a few text commands like this when I was first working on it without a GUI that were then later removed, so I'll just add those back in for the next release.  FWIW, I'm relatively confident in directly placing from the plugin these days, unless SE were to change their struct layouts, but I understand the desire for this all the same.

**Comment by PunishedPineapple** [comment]
Added back in with v1.2.0.0.
